import type { Metadata } from 'next';
import Navbar from './admin/(components)/Navbar';

export const metadata: Metadata = {
  title: 'Admin Portal',
  description: 'Generated by create next app',
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      <Navbar />
      {children}
    </section>
  );
}
